name: paseos
channels:
  - conda-forge
dependencies:
  - python>=3.12  # Updated to support Python 3.12
  - dotmap>=1.3.30  # Core non-optional dependency
  - loguru>=0.6.0  # Core non-optional dependency
  - matplotlib==3.10.0  # Core non-optional dependency
  - numpy>=1.26.0  # Updated to latest major version for Python 3.12
  - myst-parser  # For markdown math in docs
  - pyquaternion>=0.9.9  # Core non-optional dependency
  - pytest  # For tests
  - pytest-asyncio  # For tests involving async activities
  - scikit-spatial>=6.8.1  # Core non-optional dependency
  - skyfield>=1.45  # Core non-optional dependency
  - sphinx  # For docs
  - sphinx_rtd_theme  # For docs
  - toml>=0.10.2  # Core non-optional dependency
  - tqdm>=4.64.1  # Core non-optional dependency
  - trimesh>=4.0.7  # For geometric model
  - pykep==2.6.4