name: paseos
channels:
  - conda-forge
dependencies:
- dotmap
- loguru
- matplotlib
- myst-parser
- pykep
- pytest
- pytest-asyncio
- python 
- scikit-spatial
- skyfield
- sphinx
- sphinx_rtd_theme
- toml
- tqdm
