name: Docker Image CI - PASEOS

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu:22.10

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paseos:$(date +%s)
